#Makefile generated by Fortran Builder 6.0
#The following macros are machine specific
fblib = '../../../../../../Program Files (x86)/NAG/EFBuilder 6.0/lib'
NI_NAGFOR_Compiler = nagfor
NI_NAGFOR_CompOpts = -ideclient -abi=64 -g -C
NI_NAGFOR_NAGFORInfo = -gfb
NI_NAGFOR_CompOnly = -c
NI_NAGFOR_IFLAGS = 
NI_C_Compiler = nagfor =C
NI_C_CompOpts = -ideclient -abi=64 -g -Wc,-Wall
NI_C_CompOnly = -c
NI_IFLAGS = 
NI_CPP_Compiler = nagfor
NI_ALLOPTS = 
NI_Link = nagfor
NI_LibPath = -L'../../../../../../Program Files (x86)/NAG/EFBuilder 6.0/lib64' -L$(fblib) 
NI_LDFLAGS = 
NI_RM = fbrm 

#File extensions used in this Makefile
.SUFFIXES:
.SUFFIXES: .FOR .o .f90 

#Output file
NI_OUTPUT = Tesina.exe

#Target name
NI_TARGET = Tesina.exe

#Object files
NI_OBJS =	 \
	SIMP1.o \
	SIMP2.o \
	SIMP3.o \
	SIMPLX.o \
	testcase.o

#Depend Object files
NI_DOBJS =	 \
	SIMP1.o \
	SIMP2.o \
	SIMP3.o \
	SIMPLX.o \
	testcase.o

#Prospective Module files
NI_MODS =	
#Fortran Information files
NI_FIFS =	 \
	SIMP1.fif \
	SIMP2.fif \
	SIMP3.fif \
	SIMPLX.fif \
	testcase.fif

#Library files
NI_LIBS = 

#Dependencies
NI_EQ==
NI_SC=\;
SIMP1.o:	SIMP1.FOR
SIMP2.o:	SIMP2.FOR
SIMP3.o:	SIMP3.FOR
SIMPLX.o:	SIMPLX.FOR
testcase.o:	testcase.f90

#Default make target rule
$(NI_TARGET):$(NI_OBJS)
	@echo @link
	$(NI_Link) -o $(NI_OUTPUT) $(NI_LibPath) $(NI_DOBJS) $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)

#Other rules
SIMP1.o:
	@echo @nagfor SIMP1.FOR
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) SIMP1.fif -c SIMP1.FOR
SIMP2.o:
	@echo @nagfor SIMP2.FOR
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) SIMP2.fif -c SIMP2.FOR
SIMP3.o:
	@echo @nagfor SIMP3.FOR
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) SIMP3.fif -c SIMP3.FOR
SIMPLX.o:
	@echo @nagfor SIMPLX.FOR
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) SIMPLX.fif -c SIMPLX.FOR
testcase.o:
	@echo @nagfor testcase.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) testcase.fif -c testcase.f90

#Rebuild rule
all:clean $(NI_OBJS)
	@echo @link
	$(NI_Link) -o $(NI_OUTPUT) $(NI_LibPath) $(NI_DOBJS) $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)

#Clean rule
clean:
	$(NI_RM) $(NI_OUTPUT) $(NI_DOBJS) $(NI_MODS) $(NI_FIFS) fbvalwatch.vwi

#Clean all rule
clean_all:
	$(NI_RM) '*.exe' '*.a' '*.dll' '*.o' '*.mod' '*.fif' '*.bak' fbvalwatch.vwi
